### PR TITLE
Haddocking

### LINKED ISSUE #11: Documenting the code with Haddock
Since we're at a reasonably stable place with most of the core functionality, it might be time to step back and tackle documenting all of the modules using [Haddock](https://www.haskell.org/haddock/), a tool that ships with every standard Haskell installation to generate nicely formatted documentation using special comment syntax. It's very intuitive, and the results are styled precisely to ship a package to Hackage.

We can use this issue to track what modules still need documentation. Here's a checklist we can tick off as we complete documentation; this issue should also be updated as any new features are merged into `develop`:

- [x] ChordSubs.hs
- [x] Diatonic.hs
- [ ] Scale.hs

### Base

- [x] CQuality.hs
- [x] ChordSymbol.hs
- [x] Heliotonic.hs
- [x] IQuality.hs
- [x] Interval.hs
- [x] PitchClass.hs

#### Base.Chord

- [x] Chord.hs
- [x] ChordSymbol.hs
- [x] ChordShape.hs
- [x] Extension.hs
- [x] HighestNatural.hs
- [x] RawChord.hs
- [x] Root.hs
- [x] Sus.hs

#### Base.Core

- [x] Accidental.hs
- [x] Note.hs

##### Base.Core.Quality

- [x] CQuality.hs
- [x] IQuality.hs

### Common

- [x] Utils.hs

### Language

- [x] Parser.hs

### PR DESCRIPTION
**Pull request by edwisdom**
## Highlights
1. Documented all of the code we have except for the Scales module, since it's soon-to-be refactored. 
2. Only 2 source code changes, which are minor show changes and lifting a function into a Maybe that only propagated very locally.
3. Lots of pretty small TODOs that we can nail down in a separate branch for housekeeping

This PR resolves #11 -- @ChrisEPhifer feel free to look over in case there's some glaring accidental error, and then we should be good to merge and close this!

### CODE REVIEW

**Comment by ChrisEPhifer** [comment]
This is extra annoying, but I notice that most of the modules have top-level comments (that I believe were intended to be Haddock-renderable documentation) that are missing the '|' character (which is how Haddock knows "this is something I should render as documentation". Unfortunately, you'll have to go through all of the modules and add that pipe to all the comments you meant to be documentation :(

**Comment by edwisdom** [comment]
Welp, I'm on it

**Comment by edwisdom** [comment]
Good to go?

**Comment by ChrisEPhifer** [comment]
Yep! Looks good.

**Pull request merged**
