### PR TITLE
Typeclasses and Refactoring

### PR DESCRIPTION
**Pull request by ChrisEPhifer**
I want to do a little bit more with this before merging, but this PR accomplishes a few things:

* Replace `invert` functions with an `Invertible` typeclass (per #14)
* Move the `Diatonic`, `ChordSubs`, and `Scale` modules into the rest of the module hierarchy
* Rename `ChordShape`, `ChordSymbol`, and `ChordSubs` modules to simply `Shape`, `Symbol`, and `Subs` (since the modlue hierarchy already has the name `Chord`, e.g. `Base.Chord.Shape`)

Other things I might do:

* Break down the `Scale` module into more pieces
* Identify other typeclasses to implement

### CODE REVIEW

**Review by edwisdom — COMMENTED** [review]
Love adding the stray modules into the hierarchy! The invertible type class makes a lot of sense for intervals, modes, and scales as written. One thing I'm wondering is inversion for chords -- for that, the property is something more like (invert i) . (invert -i) = id. Does that still work with the invertible type class as currently written?

**Comment by ChrisEPhifer** [comment]
Oh, good point about `invert`... The typeclass could still be used for chords; the law as stated is just too strict (and in fact it's not so easy to write down a law/ or laws that cover everything.) I'll get rid of that documentation.

**Comment by ChrisEPhifer** [comment]
Actually, maybe this is a sufficient law: There exists `n` such that `invert` composed with itself `n` times is the identity function.

**Comment by edwisdom** [comment]
Yes! I think that works for sure

**Comment by ChrisEPhifer** [comment]
@edwisdom there's one more set of changes I want to get going on this branch, namely splitting up `Base.Scale` and getting it mixed into the module tree in a sensible way.

Let me know if you think any of these other changes don't actually make sense :)

**Review by edwisdom — COMMENTED** [review]
Great catch on the docs on uncurry. These module switches all look reasonable, and I definitely think breaking up the scales/modes feels like the next logical thing to do.

**Comment by edwisdom** [comment]
Also, unless you think it makes sense for me to add some instance functions for this branch or work on the small TODOs in the docs, I think I'm gonna open a new issue to start thinking about pitches/voicings -- just writing down some algebraic laws and function signatures so that we have something to work with as we pivot to that next phase (along with #6).

**Comment by ChrisEPhifer** [comment]
Honestly I didn't see anything worth breaking out into more typeclasses here just yet, so I think opening a new ticket and starting that work totally makes sense.

At some point in the near future I'll get started on #6, what's nice about parser combinators is they've very easy to transition to parser generators (the other direction not so much.)

**Comment by ChrisEPhifer** [comment]
@edwisdom Just pushed some reorganization of the Scale-adjacent modules; let me know what you think about that. Take note I got rid of some function exports, so for future work you may have to mess around with what we're actually going to provide from these modules.

In particular, there's some functions that live in `Base.Scale.Mode` now that I'm a bit wary of, if only because they're functions on sets of intervals rather than modes (and are named in ways implying they actually act on `Mode`s proper.)

I'll leave it to you to mess with any naming of these things; don't hesitate to check out this branch and just make the edits directly :) Everything also needs documentation if you're up for it; if not, happy to take care of that later tonight or tomorrow at some point.

**Review by edwisdom — COMMENTED** [review]
These refactors all make a ton of sense -- don't know if I commented before but the baseModeToIntervals is a LOT cleaner this way. Will document this now!

**Pull request merged**
