### PR TITLE
WIP: Chord Structure

### LINKED ISSUE #16: Chord Shapes, Chord Symbols, and Chords
It'd probably be helpful from a naming and clear-thinking standpoint to distinguish between these such that...

ChordShape <- everything Chord currently is without the Root
ChordSymbol <- Root ChordShape
Chord <- (ChordSymbol, [Note]), i.e. currently ExpChord

These would allow ChordShape to mirror the existing Mode type, and ChordSymbol to mirror the existing Scale type

### PR DESCRIPTION
**Pull request by ChrisEPhifer**
This PR resolves #16.

For the purposes of this PR, I made sure that the `Chord` module has the same interface it had before (e.g. there is a function `getQuality :: Chord -> Quality`, even though the `Quality` is actually stored in the values of type `ChordShape`.)

The reason I labeled this as a 'question' is the extant code using chords are (mostly) using what is now known as `ChordSymbol` - if you'd like, @edwisdom, before we actually merge this into `develop`, I can comb through the other modules currently using the old version of `Chord` and update them to work on `ChordSymbol`, instead. I think this is a desirable change, since much of the work necessary to get a chord's notes works on the `ChordSymbol` to get there.

### CODE REVIEW

**Review by edwisdom — COMMENTED** [review]
The types and names all look great! I think we should figure out what to do with chordToIntervals and chordToNotes in Lib before going ahead-- whereas chordToIntervals should work on all 3 (ChordShape, ChordSymbol, Chord), chordToNotes should only work on the latter 2. Not sure what the right abstraction is so that we can maybe make these functions polymorphic -- same for our transpose functions.

**Comment by edwisdom** [comment]
I also agree that we should change wherever we have Chord and actually mean ChordSymbol -- I can do that for the ChordSubs branch once this is merged in with the other tweaked code.

**Comment by ChrisEPhifer** [comment]
Hmm. Well, typeclasses are what come to mind as the right abstraction for those functions, but they're very ad hoc, and I'm inclined to just give the functions unique names (`chordShapeToIntervals`, `chordSymbolToIntervals`, etc.)

I think for the time being I'll write those functions outside of a typeclass, and if we decide later that having unique names is annoying, we can always retrofit.

I'll also transition `Chord` to `ChordSymbol` wherever appropriate.

Last thing: Note I'm not adding documentation for code that isn't new (aka I didn't write any documentation for `Base.Chord.Chord`), since you were already working on that in #11.

**Comment by edwisdom** [comment]
Yes, I'll open a separate branch and document all of the old code there! And it makes sense to hold off on this type class for now.

**Comment by ChrisEPhifer** [comment]
@edwisdom As I've been working more on this, I think the changes are going to be a little more substantial than originally anticipated.

Essentially, what I'm running into now is the fact that `ChordShape`, `ChordSymbol`, and `Chord` all share an interface (namely, the functions providing access to quality, extensions, suspensions, etc.) Because this is so pervasive, a type class is really needed in order to not be sad.

This is a long way of saying that I probably won't get this done tonight; there's a bunch of stuff that needs to move around for this to make sense. On the bright side, some of this reorganization would have probably been its own effort, anyway (I planned on basically nuking `Lib` and distributing its functions to more appropriate modules, anyway, and this effort will get a pretty significant chunk of that work done.)

I'd appreciate any thoughts you have on what to call these type classes. They will, in fact, encompass what we were discussing above: Types that admit conversion to intervals, and types that admit conversion to notes. Additionally, they'll contain the various accessor functions we've been defining (shape stuff in the former, root stuff in the latter. The latter will also require that the type be an instance of the former.)

Currently, I'm thinking about something like this: 

```haskell
class Chordal a where
  quality :: a -> Quality
  highestNatural :: a -> HighestNatural
  extensions :: a -> [Extension]
  suspension :: a -> Sus
  toIntervals :: a -> Set Interval

class Chordal a => Rooted a where
  root :: a -> Note -- Assuming the change not-yet-integrated from #17 
  toNotes :: a -> [Note]
```

The second class asserts that to be a `Rooted` type, you must also be `Chordal`.

**Comment by ChrisEPhifer** [comment]
@edwisdom OK! I did a whole bunch of reorganizing and things feel a bit cleaner now. Definitely take a look at the changes I implemented and let me know what you think.

I'll try to deal with the merge conflicts that got introduced, there's a bunch of them haha.

**Review by edwisdom — APPROVED** [review]
This all looks beautiful! Love the naming too -- we're in somewhat uncharted territory, so there's no accepted name for these abstract concepts, but chordal and rooted make intuitive sense. I think it'd be worth looking at Modes and Scales next to see if we can do something like this for them since they have similar interfaces as far as having a toNotes or toIntervals or transpose function.

**Comment by ChrisEPhifer** [comment]
@edwisdom I just pushed an absolutely huge number of commits; these should have integrated this work into all of your `ChordSubs` stuff. If you wouldn't mind, please take a really careful look at everything (there was a lot to change/shuffle around, and I just want to make sure I didn't break anything you've implemented.)

**Comment by ChrisEPhifer** [comment]
Also, regarding your comment about thinking about other abstraction opportunities over modes/scales, I was actually planning on starting another branch after this one is merged in to do just that, plus some reorganization of those modules since things are just kind of wherever at the moment.

It'll probably resolve the ticket I have open about type classes (can't link to it easily, I'm on mobile; will edit when on my computer.)

**Review by edwisdom — APPROVED** [review]
I looked fairly carefully through all the changes, especially where it was more than just the type signature being changed, and they all seem like they preserve the functionality!

**Pull request merged**
